### PR TITLE
better write stream

### PR DESCRIPTION
**Pull request by calvinmetcalf**
great module, but the write stream doesn't quite follow the conventions of a regular write stream, this fixes it to make sure it acts like a normal write stream, I was having some issues where it would look like it was done but the data wasn't written yet

### CODE REVIEW

**Comment by jb55** [comment]
we removed this awhile back #5,#7 since we'd rather use the official stream upload implementation from aws-sdk. Perhaps there is a way to fix the issue you're referring to without the additional dependency?

**Comment by calvinmetcalf** [comment]
the issue is just that since you have that proxy stream in the way, that one ends before it's actually done uploading and looking back through the aws skd it doesn't look like they expose a real stream

**Comment by calvinmetcalf** [comment]
would it be helpful if I made a test that fails without this pull but succeeds with it to demonstrate the issue better ?

**Comment by jb55** [comment]
I'll just push a new major version. Those who are happy with the current behaviour can stay on 1.*

**Comment by jb55** [comment]
available at 2.0.1

**Comment by calvinmetcalf** [comment]
woot thanks!

**Pull request merged**
