### PR TITLE
Refactor tests & optimize package size

### PR DESCRIPTION
**Pull request by vladimyr**
Hi @jb55 👋 

thank you for creating this useful package 👍 
I did some tweaks here:
- added `.editorconfig` & actual license file
- added more badges on readme
- omitted tests and other unused stuff from published tarball: https://npmfs.com/package/s3-blob-store/4.1.0/
- linted code using [`eslint-config-semistandard`](https://github.com/standard/eslint-config-semistandard)
- refactored test suite to use mock S3 service provided by [`s3rver`](https://npm.im/s3rver)
- swapped `lodash.clonedeep` with `Object.assign` calls to decrease package install size
- updated `debug` dependency to latest version

### CODE REVIEW

**Comment by vladimyr** [comment]
I've had to drop node v6 and v7 from Travis testing matrix due to `s3rver` not supporting them.

**Comment by jb55** [comment]
This is great!

**Comment by vladimyr** [comment]
Glad that you like it 🎉

**Comment by vladimyr** [comment]
Just please when you get time publish new release on npm.

**Comment by jb55** [comment]
published @4.1.1

**Pull request merged**
