### PR TITLE
Adds the `.move` API

### PR DESCRIPTION
**Pull request by dweinstein**
missing tests but first let me know if this is an acceptable feature.

### CODE REVIEW

**Comment by jb55** [comment]
It's actually possible to make this work for all abstract blob stores:

```js
function move(store, from, to, done) {
  store.createReadStream(from)
  .pipe(store.createWriteStream(to, wrote))

  function wrote(err) {
    if (err) return done(err)
    store.remove(from, done)
  }
}
```

haven't tested this, but should work...

**Comment by dweinstein** [comment]
yeah that's more generic for sure... Ill give it a shot. I was having some pretty bad luck with s3 copies where it would say a key didn't exist even though an upload had finished

**Comment by dweinstein** [comment]
I guess while that might be generic it could also be less optimal for local filesystem moves and large files.  ISTM if Amazon ever adds an API to move files within a bucket cheaply you'd be downloading the whole file before sending it back up. I guess if they ever make copyObject cheap then we would get the benefit of any optimization they could make behind the scenes.

**Comment by jb55** [comment]
Yes of course, with any abstraction you pay these costs. Adding additional features to a generic api instance that no other abstract blob store shares doesn't make much sense to me. This library is simply meant to be an implementation of the abstract-blob-store spec, it is not meant to be an aws-sdk porcelain. It sounds like you're better off just using the aws sdk directly if you're worried about performance implications.

If you do get issues with my code sample that probably is a bug though, and should be fixed.

Thanks for the PR, but I have to politefully decline it.

Cheers,

**Pull request closed without merging**
